### PR TITLE
Rename presentations to match downloads

### PR DESCRIPTION
**Pull request by sbesson**
This should simplify the copying over to downloads /cc @ximenesuk

### CODE REVIEW

**Comment by sbesson** [comment]
@manics is `omero_at_scale-infrastructure_idr` the official name to go along other presentations at http://downloads.openmicroscopy.org/presentations/2016/Users-Meeting/Workshops/ ?

**Comment by manics** [comment]
@sbesson I guess it should match the presentation title, so how about "OMERO at scale How we built the IDR"?

**Comment by sbesson** [comment]
Pushed

**Comment by manics** [comment]
Thanks. I think the link in https://github.com/sbesson/presentations/blob/b5b858bb5da306108c6c281d0d0ac0e50ac18669/2016/Users-Meeting/Workshops/OMERO-at-scale-How-we-built-the-IDR/index.html#L166 needs changing to `../Extensible-Import/index.html` (need a build to check though)

**Comment by sbesson** [comment]
Pushed

**Comment by ximenesuk** [comment]
This looks fine. I'll merge, copy over to downloads and ask for people to check their own talks again from there.

**Pull request merged**
