### PR TITLE
Starting point for ImageJ conference lightning talk

### PR DESCRIPTION
**Pull request by melissalinkert**
I expect to make many more edits yet, but merging this should at least let us
submit a stable URL for the slides.  Currently almost a direct copy of
the similar talk from Paris 2015, with the title fixed and the obvious Paris-specific things removed.

### CODE REVIEW

**Comment by joshmoore** [comment]
Ok to merge then?

**Comment by jburel** [comment]
Yep
I have one PR to open too
So we can then send the link

**Comment by jburel** [comment]
Merging

**Comment by melissalinkert** [comment]
Thanks - sending email.

**Pull request merged**
