### PR TITLE
Add ome/presentation-20171110-gre-symposium

### PR DESCRIPTION
**Pull request by manics**
Follow-up from https://github.com/ome/presentations/pull/74

### CODE REVIEW

**Comment by mtbc** [comment]
I didn't realize we used submodules here; that won't confuse any consumers? Does this get staged anywhere?

**Comment by manics** [comment]
We agreed to use submodules in https://github.com/ome/presentations/pull/74#issuecomment-347171428

**Comment by mtbc** [comment]
Aha, if I merge this in locally then do `git submodule init`, `git submodule update` then I do seem to end up with stuff. Don't know if we then want a link to it from somewhere but it seems to me that this PR brings in the version that GH deploys on the web.

**Comment by sbesson** [comment]
Similar to https://github.com/openmicroscopy/prod-playbooks/pull/119#pullrequestreview-169203302, the deployment of this PR to https://downloads.openmicroscopy.org/presentations/ is currently blocked by networking issues while cloning the submodule.

**Comment by sbesson** [comment]
Now deployed at http://downloads.openmicroscopy.org/presentations/2017/20171110-gre-symposium/html/#/

**Pull request merged**
