### PR TITLE
POTN Omero-Web workshop

### PR DESCRIPTION
**Pull request by will-moore**
Also includes a previously not-committed presentation from 2016.

### CODE REVIEW

**Comment by jburel** [comment]
this should minimally be split into 2 PRs one for 2016, one for 2017
and re-use the common folders: ``_images`` and ``_reveals-js`` for the 2017 presentation

**Comment by sbesson** [comment]
For the 2017 workshop, https://github.com/ome/presentations/pull/65 shows how to re-use the shared folders without affecting the existing layout/href using symlinks.

**Comment by will-moore** [comment]
I've merged in ome/master and fixed links to ```../_images/logos...```.
Haven't updated links to use the shared ```../_reveal-js/``` since this is an older version than the one I'm using and some things break.
Just pushing changes but this is taking a *really* long time (20 mins so far) so I might have to leave it to run overnight:
```
ls31618:presentations wmoore$ git push gh HEAD
Counting objects: 552, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (275/275), done.
Writing objects:  59% (326/552), 43.52 MiB | 43.00 KiB/s   
```

**Comment by will-moore** [comment]
OK, so I removed the POTN 2017 Omero-Web from this PR and moved it to a new PR: #66

**Comment by sbesson** [comment]
In order to reconcile the state of this repository with the deployment under http://downloads.openmicroscopy.org/presentations/, merging this PR as it is (and the companion ones).

Once both are in sync, we can look into extracting 1- the reveal-js themes and 2- some images so that we stop duplicating material for each new presentation.

**Pull request merged**
