### PR TITLE
Add GBI OMERO presentation

### PR DESCRIPTION
**Pull request by pwalczysko**
Adding OMERO presentation in advance of the course on Tuesday

cc @jburel

### CODE REVIEW

**Comment by jburel** [comment]
The final slide with logos needs to be updated. I am pretty sure this was done in previous presentations e.g. eosc-life is missing

**Comment by pwalczysko** [comment]
@jburel thank you, commit pushed

**Comment by pwalczysko** [comment]
@jburel Are we good to deploy here for tomorrow ?

**Comment by jburel** [comment]
thanks for the changes

**Pull request merged**
