### PR TITLE
Ops/Monitoring Workshop (WIP)

### PR DESCRIPTION
**Pull request by kennethgillen**
WIP still

### CODE REVIEW

**Comment by sbesson** [comment]
@kennethgillen main initial feedback is that we probably want a different structure. Depending on how you and @manics combine your talks, should think generally be organized under `2018/Users-Meeting/Workshops/OMERO.ops/`?

**Comment by kennethgillen** [comment]
@sbesson - both talks are combined in this slide deck.

**Comment by jburel** [comment]
Should the ``.sh`` files not supposed to be on GitLab?
strange to have them in this repo

**Comment by kennethgillen** [comment]
I had to put them somewhere for now - I don't feel it's strange to have kept them alongside the rest of the presentation. To have to push/pull from >1 repos while developing my presentation doesn't make sense to me at least. 

Yes, @joshmoore said he'd show me how/where to put them on gitlab, but we've not got to that yet. This is still WIP and there will be changes to the slides throughout the day.

**Comment by sbesson** [comment]
The latest version was rehearsed yesterday. Merging for a first round of deployment on downloads. 

On the shell scripts, agreed that the short-term goal is to push these to an incubator repo. If we can get there by Thursday, :+1:, otherwise if attendees express interest, it might be worth trying to sort out on Friday.
Note also that reveal allows you to directly embed snippets which would save the shell script -> png screenshot step. But there might be graphical reasons not to do so.

**Comment by kennethgillen** [comment]
@sbesson - thanks for the tip, but i found the bash highlighting by the reveal plugin we're using to be incorrect/wrong, and not as extensive as my own.

**Pull request merged**
