### PR TITLE
Tim2023

### PR DESCRIPTION
**Pull request by pwalczysko**
Presentation for next week.

The folder name is 

``...presentations/2023/TiM-Munsingen/``

cc @jburel

### CODE REVIEW

**Comment by pwalczysko** [comment]
@jburel Could you please have a look ? I need this for the workshop on Monday.

**Comment by jburel** [comment]
idr image is missing

**Comment by pwalczysko** [comment]
> idr image is missing

@jburel sorry, image pushed, thanks

**Comment by jburel** [comment]
Looks good now thanks

**Pull request merged**
