### PR TITLE
Add presentation for seminar Japan

### PR DESCRIPTION
**Pull request by pwalczysko**
Adding a presentation for the seminar in Okazaki. 

cc @jburel

### CODE REVIEW

**Comment by pwalczysko** [comment]
@jburel changed as discussed (for Thurs workshops intro only, focus on OMERO.figure and publication).

**Comment by pwalczysko** [comment]
@jburel I think this could be enough for a 60 minutes seminar: 30 slides is 2 mins per slide, and some of them will be quite long to go over, as there are embedded videos with features.

Will stop adding and see what you think.

**Comment by jburel** [comment]
* Annotations: indicate filter: Maybe a screenshot on top of the centre panel will be useful
* OMERO.iviewer: screenshot will z and t will be great to show the feature since you highlighted the z-slider

**Comment by pwalczysko** [comment]
Fixes pushed

**Pull request merged**
