### PR TITLE
OME2017 » Engineering the IDR

### PR DESCRIPTION
**Pull request by manics**
Add "OME2017 » Engineering the IDR" presentation

### CODE REVIEW

**Comment by sbesson** [comment]
@manics raised the fact that the embedding of `reveal-js` might still be necessary for using some of the functionalities. (https://github.com/hakimel/reveal.js/#speaker-notes if I remember correctly). Would a symlink to `../_reveal-js` work ?

Shared images should be unified with what is available under https://github.com/ome/presentations/tree/gh-pages/2017/Users-Meeting/Workshops/_images

**Comment by manics** [comment]
I could only get it to work if `index.html` was in the directory containing the `reveal-js` content. If you can figure out how to make it work from outside I'll update this.

**Comment by manics** [comment]
> Shared images should be unified with what is available under https://github.com/ome/presentations/tree/gh-pages/2017/Users-Meeting/Workshops/_images

I tried using `../_images/` but that fails to resolve in speaker mode.

**Comment by sbesson** [comment]
Is it also the case if you symlink `../_images` as in https://github.com/sbesson/presentations/commit/0b1cc4c31849ccfd5b257cf27bd8cab6cfd6b010?

As for `reveal-js`, an additional issue is that this PR is using the latest version `reveal-js 3.5.0` while the shared theme is currently an older version. Trying to unify the styling could impact either this presentation or the other existing ones. Given the late hour, we likely will not have the bandwidth to resolve this dependency conflict and it's unfortunate it was not raised and discussed it as part of https://github.com/ome/presentations/pull/52.

Assuming we keep generating content using `reveal-js`, there might be a general agreement to be made on how we manage versions use across the board and how we can package, consume and distribute these presentations.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [PRESENTATIONS-merge#21](https://ci.openmicroscopy.org/job/PRESENTATIONS-merge/21/). See the [console output](https://ci.openmicroscopy.org/job/PRESENTATIONS-merge/21/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - 2017/Users-Meeting/Workshops/Introduction-to-Bio-Formats/images

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [PRESENTATIONS-merge#22](https://ci.openmicroscopy.org/job/PRESENTATIONS-merge/22/). See the [console output](https://ci.openmicroscopy.org/job/PRESENTATIONS-merge/22/consoleText) for more details.
Possible conflicts:
  - Conflict detection failed
    - 2017/Users-Meeting/Workshops/Introduction-to-Bio-Formats/images

**Comment by sbesson** [comment]
See https://github.com/ome/presentations/pull/64#issuecomment-306414394

**Pull request merged**
