### PR TITLE
Okinawa

### PR DESCRIPTION
**Pull request by jburel**
Add workshop for okinawa

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
ABIS, not ABIs

**Comment by jburel** [comment]
@pwalczysko correct version is ABiS see http://www.nibb.ac.jp/abis/gbi-abis_training

**Comment by pwalczysko** [comment]
Did you want to go with "knime" for the slide number 6 ? Maybe better Matlab ?

**Comment by pwalczysko** [comment]
The slide with the image I did recently is missing.

see http://downloads.openmicroscopy.org/presentations/2018/OOW-Kobe/OMERO-Workshop/#/22

**Comment by jburel** [comment]
@pwalczysko done

**Comment by pwalczysko** [comment]
Looks good. Ready to merge FMPOV. Thank you

**Pull request merged**
