### PR TITLE
New presentation 2018/TIM-Dusseldorf

### PR DESCRIPTION
**Pull request by will-moore**
Presentation for workshop at https://trello.com/c/XItmZ9Tn/193-tim-12-14-03-2018-duesseldorf
See http://www.tim2018.de/

Staged at http://will-moore.github.io/presentations/2018/TIM-Dusseldorf/

5minutes max intro

### CODE REVIEW

**Comment by hflynn** [comment]
👍 Looks good, no typos that I've noticed

**Comment by pwalczysko** [comment]
Replace ``Dusseldorf`` with ``Düsseldorf`` ("umlaut" ü )

**Comment by will-moore** [comment]
Happy for this be merged @jburel ?
It would be nice, but not essential to have it deployed to downloads.openmicroscopy.org/presentations/ before our workshop on Tuesday. Many thanks,
cc @sbesson

**Comment by jburel** [comment]
@will-moore looks good.
Merging I will discuss with @sbesson on monday

**Comment by will-moore** [comment]
@jburel @sbesson Any idea if this can go live by tomorrow afternoon? We don't need it for the presentation, but it might be nice to make the url "public". Cheers,

**Comment by jburel** [comment]
As @sbesson  indicated on the card, this requires some changes in playbook we won't have time to do it for this afternoon

**Pull request merged**
