### PR TITLE
Index fix and new presentations for 2017

### PR DESCRIPTION
**Pull request by sbesson**
Fixing https://trello.com/c/lVJmUPg9/18-ome-2016-links-on-http-ome-github-io-presentations-are-broken for the links of 2016 and adding new stub folder for 2017 Users meeting presentation.

@hflynn @jburel thoughts about getting these merged quickly so that we don't conflict and people can list their presentations in the top-level index?

### CODE REVIEW

**Comment by joshmoore** [comment]
I'm ok with the fast merging but slightly worried about having photos of everyone N times :)

**Comment by sbesson** [comment]
I am completely fine with starting to reduce the duplication (same goes for embedded `reveal-js` theme to some extent). Are you proposing a common folder in this repo or completely externalizing the resources?

**Comment by hflynn** [comment]
Yeah, I was just wondering if we needed all these css themes?

**Comment by sbesson** [comment]
Moved the images out of the PR. For the CSS, all the examples of usage of the reveal-js theme in the wild are embedding the js/css. Assuming we agree internally, we could however use a unique theme under e.g. ` 2017/Users-Meeting/Workshops/reveal-js`.

**Comment by joshmoore** [comment]
(:+1: for sharing a theme and if there's going to be anything pushed here :+1: for rebasing away the PNGs)

**Comment by sbesson** [comment]
@joshmoore Force pushed, the proposed layout is

```
2017/Users-Meeting/Workshops/images                 shared images
2017/Users-Meeting/Workshops/reveal-js               shared theme
2017/Users-Meeting/Workshops/XXXX/index.html  workshop
````

**Comment by hflynn** [comment]
Works for me

**Comment by jburel** [comment]
works for me. About to start working on the import presentation
If we are all ok, let's merge
@joshmoore ok with proposed layout

**Comment by joshmoore** [comment]
:+1:

**Pull request merged**
