### PR TITLE
Workshop further updates

### PR DESCRIPTION
**Pull request by kennethgillen**
Updates to slides. https://github.com/ome/presentations/commit/ad7b978ca6c2f9a8a3835d51ecd0667962675d7d was as-presented at #OME2018

### CODE REVIEW

**Comment by sbesson** [comment]
Is this ready for final review/integration under downloads @kennethgillen ?

**Comment by kennethgillen** [comment]
@sbesson  - I think it'd be nice to pull Simon's grafana slides into the 'correct' place where the live demo happened. At the moment they are a static backup version of the live demo, in case network was down, slightly hidden in a reveal "down arrow" slide set at the end.

@manics, what do you think?

**Comment by kennethgillen** [comment]
@sbesson - Simon's demo slides have now been exposed and put in the right place. I've also added annotations for the slides where I spoke my points and you wouldn't get the point with just the original slides.

i.e. ready for review and merge.

**Comment by sbesson** [comment]
Now deployed live at https://downloads.openmicroscopy.org/presentations/2018/Users-Meeting/Workshops/OMERO.ops

**Comment by kennethgillen** [comment]
Thanks @sbesson !

**Pull request merged**
