### PR TITLE
OME 2020 OMERO Systems Installation and Configuration workshop

### PR DESCRIPTION
**Pull request by manics**
OME 2020 OMERO Systems Installation and Configuration workshop

### CODE REVIEW

**Comment by jburel** [comment]
Why so many files modified?
Can you re-use files under template and create a symlik as we have done for the other presentations?

**Comment by manics** [comment]
It's copied from https://github.com/ome/rseconuk2019-idr/
I haven't checked for differences between the reveal-js version in this repo

**Comment by manics** [comment]
1639 of the files are bundled fontawesome-free-5.10.1-web/ icons

**Comment by manics** [comment]
I've just tried symlinking the other files and it didn't work- looks like it's missing some plugins amongst other things

**Comment by manics** [comment]
I could try and add a new template if you want to suggest a name? Or leave that for the future?

**Comment by jburel** [comment]
Why can you use what we have all been using?

**Comment by manics** [comment]
We have this discussion every year 😀
The current version is too old (reveal-js `2.8.2` vs the current `4.0.0`) has several bugs, and does't support some of the newer layout options.

I've added reveal-js and font-awesome at the top level of this repo:
- `revealjs-4.0.0`
- `fontawesome-free-5.10.1-web`

**Comment by jburel** [comment]
If you want to keep the original format, we will follow the same pattern as we do. We will have a separate repo with your presentation and add it as submodule
e.g. https://github.com/ome/presentation-20171110-gre-symposium

**Comment by manics** [comment]
Fair enough, I'll do that. It's what I started with but I didn't think people would be happy with another submodule.

**Pull request merged**
