### PR TITLE
Elmi adjustments

### PR DESCRIPTION
**Pull request by jburel**
* Change server name
* Fix path to logo
cc @pwalczysko

### CODE REVIEW

**Comment by kennethgillen** [comment]
Logo renders, link to outreach works.

Looks good to me.

**Comment by sbesson** [comment]
@jburel do you need this deployed asap or for the session tomorrow? do you have other changes upcoming?

**Comment by jburel** [comment]
I don't think we will have more changes
It can be merged and deployed

**Comment by sbesson** [comment]
Deployed live - see http://downloads.openmicroscopy.org/presentations/2018/ELMI-Dublin/OMERO-Workshop/#/16

**Pull request merged**
