### PR TITLE
Gothenburg

### PR DESCRIPTION
**Pull request by pwalczysko**
Adding presentation for tomorrow.

Note that the change in the reveal.min.css file https://github.com/ome/presentations/commit/f5b385af971c23bd878a1eda9bf51bb09676a830 is removing the forced hyphen-addition which was very often breaking the word "Workshop" on the title slide.
I have made changes only in 4 parameters, as specified in https://stackoverflow.com/questions/22388734/how-to-prevent-line-breaks-on-reveal-js-at-headline

Screen Shot 2020-11-26 at 11 54 52

But because our reveal.min.css is written on one single line (line 7), git is showing the diff as a complete rewrite of that css.
Nevertheless, the change works and it apparently does not break anything else. 

Berfore the change in the reveal.min.css https://github.com/ome/presentations/commit/f5b385af971c23bd878a1eda9bf51bb09676a830:

Screen Shot 2020-11-26 at 12 13 52

After the change in the reveal.min.css https://github.com/ome/presentations/commit/f5b385af971c23bd878a1eda9bf51bb09676a830
Screen Shot 2020-11-26 at 11 55 00
:

cc @jburel @will-moore

### CODE REVIEW

**Comment by jburel** [comment]
Have you checked the impact on other presentation?
maybe revert that change due to the short turnaround and we can check the change when we have a bit of time

**Comment by manics** [comment]
You can override the problematic style in this presentation only instead of making a global change.

**Comment by pwalczysko** [comment]
@jburel @manics  Reverted and changed the style only for this presentation, pushed.

**Comment by jburel** [comment]
Looks good, thanks for reverting the change

**Pull request merged**
