### PR TITLE
Add Lisbon presentation

### PR DESCRIPTION
**Pull request by pwalczysko**
Adding a presentation for next week based on ELMI 2019.

cc @jburel

### CODE REVIEW

**Comment by mtbc** [comment]
Staged at http://snoopycrimecop.github.io/presentations/2019/Lisbon/OMERO-workshop/.

**Comment by jburel** [comment]
Maybe update the IDR screenshot

**Comment by pwalczysko** [comment]
@jburel Fixed

**Comment by jburel** [comment]
Thanks
Merging

**Pull request merged**
