### PR TITLE
Add distributed features slides

### PR DESCRIPTION
**Pull request by simleo**
Adds `2016/distributed-features-feb-16`

### CODE REVIEW

**Comment by joshmoore** [comment]
You're welcome to cherry-pick

```
commit 50da44334acb07ab66a72bbffeb1d1711b84934f
Author: jmoore <josh@glencoesoftware.com>
Date:   Mon Feb 8 14:28:50 2016 +0100

    Add Docker support
```

if you want. You'll say the word when you're ready for this to be merged?

**Comment by simleo** [comment]
Cherry-picked, thanks. I've added some minor tweaks and now it seems good to merge.

**Comment by simleo** [comment]
The generated PDF file was not readable with Adobe Reader. 8505edd should fix it (works with `acroread` on my laptop)

**Comment by joshmoore** [comment]
:thumbsup:

**Pull request merged**
