### PR TITLE
screenshot cleanup

### PR DESCRIPTION
**Pull request by atarkowska**
screenshot cleanup

### CODE REVIEW

**Comment by sbesson** [comment]
One of the screenshot uses `trout.openmicroscopy.org`, can we revert to `localhost`?

**Comment by atarkowska** [comment]
`localhost` perhaps is not the best choice but just `omero` should be more then enough

**Comment by sbesson** [comment]
:+1:

**Comment by atarkowska** [comment]
ok I am done ;-)

**Pull request merged**
