### PR TITLE
Symlinks

### PR DESCRIPTION
**Pull request by sbesson**
This PR should:

- reduce the divergence of the image layout to facilitate the integration of https://github.com/ome/presentations/pull/60 by moving the logos under `_images/logos`
- add `reveal-js` and `images` symlinks under existing presentations to fix the current broken rendering at http://ome.github.io/presentations/2017/Users-Meeting/Workshops/Formats-Introduction/
- update the existing workshop presentations to use the new logos subdirectory and include the thank you slide

Generally this should simplify the strategy for new presentation to use a shared reveal.js theme by symlinking the theme and images in the current directory i.e.

```
cd 2017/Users-Meeting/Workshops/
mkdir NewWorkhop
ln -s ../_reveal-js reveal-js
ln -s ../_images images
# edit index.html
```

### CODE REVIEW

**Comment by sbesson** [comment]
See http://snoopycrimecop.github.io/presentations/2017/Users-Meeting/Workshops/Import/, http://snoopycrimecop.github.io/presentations/2017/Users-Meeting/Workshops/Introduction-to-Bio-Formats/ and http://snoopycrimecop.github.io/presentations/2017/Users-Meeting/Workshops/Formats-Introduction/

**Comment by jburel** [comment]
looks good
Thanks

**Review by jburel — COMMENTED** [review]
looks good

**Comment by sbesson** [comment]
Deployed (currently manually copied) under http://downloads.openmicroscopy.org/presentations/2017/Users-Meeting/Workshops/

**Pull request merged**
