### PR TITLE
Presentation for Leverhulme

### PR DESCRIPTION
**Pull request by jburel**
Today's presentation
based on recent presentation in Japan
cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
screen shot 2018-11-05 at 10 24 28
 

Would not split the word introduction in the title slide,  does not look good.

**Comment by jburel** [comment]
no split on mine :-)

**Comment by pwalczysko** [comment]
screen shot 2018-11-05 at 10 27 40

First slide above is highlighted as intro to OMERO, but first point above is Intro to OME.
Maybe "What is OME ?"

**Comment by jburel** [comment]
I will follow the same pattern as usual OMERO workshop

**Comment by pwalczysko** [comment]
Okay. Other than that, it looks good.

**Comment by jburel** [comment]
Merging and I will deploy now

**Pull request merged**
