### PR TITLE
change url

### PR DESCRIPTION
**Pull request by jburel**
use mybinder for generic repositories
I have only kept binder.bioarchive for idr specific studies

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
When I click on the badge on this line
Screenshot 2021-06-07 at 14 35 09
then the binder repeatedly reports ``404, you are requesting a page that does not exist``


Screenshot 2021-06-07 at 14 37 10

the same experience is given by clicking on 

Screenshot 2021-06-07 at 14 39 13

**Comment by pwalczysko** [comment]
the other links work, but see https://github.com/ome/presentations/pull/149#issuecomment-855935764

**Comment by jburel** [comment]
It was broken before pushing a commit now

**Comment by pwalczysko** [comment]
> It was broken before pushing a commit now

Thank you, that works, but the link on line 163 is broken in the same way (there are 2 places to fix, not just one)

**Comment by jburel** [comment]
done

**Review by pwalczysko — APPROVED** [review]

**Comment by pwalczysko** [comment]
works fine now, thank you

**Pull request merged**
