### PR TITLE
Deployment (part 2)

### PR DESCRIPTION
**Pull request by sbesson**
This PR should complete the reconciliation of the GitHub repository with the public downloads . With this PR included, we should be able to move to a straightforward `git pull` workflow to update reval-js presentations under http://downloads.openmicroscopy.org/presentations/ with the latest state of this repository.

At the moment, I excluded all reveal-js presentations prior to 2017 as well as the Jupyter notebooks presentations from the 12th Users meeting rather than trying to resync them. This means they will be treated as binary presentations and not under version control but seems like the best way to move forward with the cleanup / rationalization of this repository. We can always come back later to these presentations and re-include them.

### CODE REVIEW

**Comment by sbesson** [comment]
With the latest state of this PR 

```
sbesson@necromancer /ome/www/downloads.openmicroscopy.org/private $ git clone https://github.com/snoopycrimecop/presentations
Cloning into 'presentations'...
remote: Counting objects: 3473, done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 3473 (delta 18), reused 89 (delta 11), pack-reused 3370
Receiving objects: 100% (3473/3473), 116.64 MiB | 9.71 MiB/s, done.
Resolving deltas: 100% (1520/1520), done.
Checking connectivity... done.
Checking out files: 100% (2082/2082), done.
sbesson@necromancer /ome/www/downloads.openmicroscopy.org/private $ cd presentations/
sbesson@necromancer /ome/www/downloads.openmicroscopy.org/private/presentations $ cp -rf ../../presentations/* .
sbesson@necromancer /ome/www/downloads.openmicroscopy.org/private/presentations $ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   2017/Users-Meeting/Workshops/Import/index.html
	modified:   2017/Users-Meeting/Workshops/Jupyter-Workshops/index.html
	modified:   2017/Users-Meeting/Workshops/Jupyter-Workshops/intro_files/embed.js
	modified:   2017/Users-Meeting/Workshops/Jupyter-Workshops/intro_files/extension.js


It took 2.65 seconds to enumerate untracked files. 'status -uno'
may speed it up, but you have to be careful not to forget to add
new files yourself (see 'git help status').
no changes added to commit (use "git add" and/or "git commit -a")
```

The import modification is related to https://github.com/ome/presentations/pull/67 which had not been propagated (but should be after this PR is merged). The Jupyter-Workshops modification are whitespace-only diffs.

**Comment by joshmoore** [comment]
> The only addition is the Jupyter workshop. @joshmoore is that a right place to keep these files in?

I struggled to find a way to properly deploy this. I'm certainly open to suggestions.

**Comment by sbesson** [comment]
@joshmoore If we are unsure of the strategy but we know we revisit it for the future presentations/workshops, maybe it's worth simply adding to `.gitignore` for the time being and rationalize later?

**Comment by joshmoore** [comment]
Adding to .gitignore works for me.

**Comment by sbesson** [comment]
Force pushed. Now this PR should only contain `.gitignore` changes as well as the removal of the top-level `index.html` to preserve the navigation in http://downloads.openmicroscopy.org/presentations/

**Review by joshmoore — APPROVED** [review]
Makes sense to me. I'm not sure if longer-term we'll want to do something more/different with the index.html, but for the moment, let's get something working with all the _combined_ content. :+1:

**Comment by sbesson** [comment]
Similar to all the other strategies, I would think we could envision a landing/registration page for all these presentations in a separate location e.g at the website level as this would still allow the directory structure to remain explorable.
Merging for deployment/unification/cleanup.

**Pull request merged**
