### PR TITLE
GRE Symposium IDR/OMERO presentation

### PR DESCRIPTION
**Pull request by manics**
Presented on 2017-11-10

These are the exact slides that I used (includes horizontal and vertical slides). I can make it linear if you want.

This was created with [reveal-md](https://github.com/webpro/reveal-md)

### CODE REVIEW

**Comment by will-moore** [comment]
Wow 274 files changed!?

**Comment by manics** [comment]
It includes the generated output from reveal-md

**Comment by hflynn** [comment]
Staged at http://snoopycrimecop.github.io/presentations/2017/20171110-gre-symposium/html/#/

**Comment by will-moore** [comment]
For other reveal.js presentations we have been trying to reuse existing libs, e.g. https://github.com/ome/presentations/pull/70/files so this seems a bit excessive, but maybe it's not such a big deal.

**Comment by manics** [comment]
Everything under `html` (including all the reveal-js files) is generated by `reveal-md`

**Comment by sbesson** [comment]
Sorry for the delay here. Overall looks good but a few questions.

As this presentation is using a new format or minimally a new version of the format with a different layout, I think a couple of decisions need to be made prior to its integration.

Following the 2017 Users Meeting, a couple of concerns were raised with regard to the management of this repository:

- the growing size of this repository as each presentation kept committing source files, style files and images
- the duplication of some of the resources above for each presentation esp. images and CSS files

An initial effort was put to centralize these resources in shared directories (`_images` and `_template`). A recent set of changes somewhat challenge this proposal:

- modifying or updating a shared theme/image will affect a growing set of material - see https://github.com/ome/presentations/pull/75#issuecomment-345824362
- similarly, we might want to test a new format/version without having to modify and review existing presentations
- the workflow for consuming these shared resources might be too burdensome for the added value
- the amount of time put into this presentation format (both in terms of review and management) somewhat contrasts with other presentation formats (pptx, pdf, google slides)

While the full management of these presentations might be too costly, having a structure to organize these Web-based presentation, review them and ease the deployment under https://downloads.openmicroscopy.org/presentations/2017/ is still valuable. An intermediate proposal to keep this repo manageable would be to migrate new presentation that does not consume the existing central template like this one under its standalone repository and have `ome/presentations` consume it as a submodule i.e.

``` 
 2017/
   Team-Training/
   GRE-Symposium @ ... 
```

NB: the management of the resources (images, screenshots) will still need to be tackled eventually but this is something that might need to be done outside the scope of this repository.

Thoughts or alternate proposals welcome /cc @jburel @joshmoore @manics

**Comment by manics** [comment]
A submodule is fine with me.

**Comment by sbesson** [comment]
Closing this and leaving you to extract the presentation to a decoupled repository, we can then transfer it and register it as a submodule here.

**Comment by manics** [comment]
https://github.com/manics/20171110-gre-symposium

**Comment by manics** [comment]
@sbesson Looks like the transfer got stuck half way 😊 https://github.com/sbesson/presentation-20171110-gre-symposium Can you move it to ome when you get a chance?

**Comment by sbesson** [comment]
Sorry for the delay - see https://github.com/ome/presentation-20171110-gre-symposium

**Pull request closed without merging**
