### PR TITLE
Basel workshops

### PR DESCRIPTION
**Pull request by jburel**
Add presentations for Basel workshops
cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
For Day1 presentation:


    - in the slide screenshotted below, I think there should be some ``...`` also indicating that OMERO.insight and OMERO.web are not the only possible omero clients (we have cli and also third party apps) - atm it looks like only the web apps are limitless, all else is set in stone
    - the OMERO.figure slide has no title -> the figure itself is nice, but  the slide before it and after it have titles

screen shot 2018-08-28 at 20 23 38

**Comment by pwalczysko** [comment]
For Day 2:

   - the CLI slide is too verbose, I think the text needs breaking into couple of bullet points
   - on that slide, there is no mention of import abilities of CLI
   - there is an insight import slide in this presentation, which we did on Day1, and not on Day2 - maybe it is there just as a stepping stone to remind + get us to CLI import options ?

**Comment by jburel** [comment]
Day 2: insight slide was there to remind what we did the first day before moving to something "less visual"

**Comment by will-moore** [comment]
Looks fine.
No screenshots of other clients? Orbit, CellProfiler, Fiji etc?

**Comment by jburel** [comment]
We will cover them at length during the workshops so we opted not to show them in the presentation

**Comment by pwalczysko** [comment]
Looks all godd. Ready to merge FMPOV. Mabye we should during the Day2 talk indicate (just orally) that the CLI is a main focus (but we will do other stuff as well, jupyter, server side scripts, etc.)

**Comment by jburel** [comment]
Merging so we can deploy it

**Pull request merged**
