### PR TITLE
TOPIM-Thursday-talk initial commit

### PR DESCRIPTION
**Pull request by will-moore**
Presentations for TOPIM 2018: http://www.e-smi.eu/index.php?id=2751

One talk for Thursday (35 mins) - Staged at http://will-moore.github.io/presentations/2018/TOPIM-Crete/OMERO-Thursday/
Workshop intro for Friday (still to come)

### CODE REVIEW

**Comment by will-moore** [comment]
cc @jburel @pwalczysko outline of Thursday talk is done. Need to run-through to test timing. Update webclient screenshot, etc.

**Comment by pwalczysko** [comment]
I am having some strange semi-icon on the slide "OMERO.clients" - see left part of the screenshot below

screen shot 2018-06-27 at 17 20 05

**Comment by pwalczysko** [comment]
Looks good. Ready to merge FMPOV. 

cc @sbesson @joshmoore (see https://trello.com/c/PBrVdjCG/4-prepare-printout-for-topim as well)

**Comment by sbesson** [comment]
@will-moore @pwalczysko now deployed live at https://downloads.openmicroscopy.org/presentations/2018/TOPIM-Crete

**Comment by will-moore** [comment]
Thanks @sbesson. Looks good.

**Pull request merged**
